### ISSUE TITLE
Warning when using a en dash (–) in a string

### ISSUE THREAD

**Issue by prrrnd** [AtomLinter/linter-ruby#116] opened 2017-04-22 13:29 UTC
A picture is worth a thousand words, as _they_ say.

<img width="452" alt="screen shot 2017-04-22 at 15 25 03" src="https://cloud.githubusercontent.com/assets/2150204/25304848/e7517c70-276f-11e7-9de2-5e5b0de2387b.png">

`ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-darwin16]`
`ruby -wc path/to/file.rb` returns `Syntax OK`

Let me know if you need additional information

**Comment by BrianHawley** [comment] 2017-05-01 20:14
Note: Just like with #103, adding an encoding comment to the file fixes the issue:
```ruby
# encoding: utf-8
```

**Comment by sandstrom** [comment] 2017-05-11 13:13
This is a duplicate of #103

**Closed** 2017-05-12 17:45 UTC
Labels: duplicate
