### ISSUE TITLE
Error using other languages

### ISSUE THREAD

**Issue by artemgurzhii** [AtomLinter/linter-ruby#106] opened 2016-12-25 13:30 UTC
I'm getting this error 
![screen shot 2016-12-25 at 15 28 12](https://cloud.githubusercontent.com/assets/13109164/21471320/eacd4d4a-cab6-11e6-8067-545306c00c8a.png) when I'm not using English.

**Comment by Arcanemagus** [comment] 2017-01-06 21:03
What version of Ruby are you using? The PR you linked above isn't the proper way to set the encoding on any version I know of.

**Comment by artemgurzhii** [comment] 2017-01-06 21:05
ruby 2.3.3p222 (2016-11-21 revision 56859) [x86_64-darwin16]

**Comment by Arcanemagus** [comment] 2017-01-06 21:07
I'm not sure what the issue is then as this package is already setting the encoding in a manner that should work just fine in that version...

**Comment by artemgurzhii** [comment] 2017-01-06 21:14
I have uninstalled and then installed this packege, but still getting this error. <img width="558" alt="screen shot 2017-01-06 at 23 12 50" src="https://cloud.githubusercontent.com/assets/13109164/21733163/b2c7f072-d465-11e6-83ee-b10bef3f61f3.png">

**Comment by SpaceWhite** [comment] 2017-01-09 23:29
+1 -- I got the same error too on chinese and japanese

**Comment by SpaceWhite** [comment] 2017-01-09 23:36
I add encoding : utf-8 and it solves the error
![dsa](https://cloud.githubusercontent.com/assets/15065085/21788017/d69ca5c2-d70f-11e6-8a77-c401a7542e56.jpg)
![untitled](https://cloud.githubusercontent.com/assets/15065085/21788016/d69c3e16-d70f-11e6-899b-17343de485a8.jpg)

**Comment by artemgurzhii** [comment] 2017-01-09 23:41
Is everything else working properly?

**Comment by Arcanemagus** [comment] 2017-03-23 16:52
Thanks to the notes from @wdspkr in https://github.com/AtomLinter/linter-ruby/pull/112 we now know that on Windows and Linux the option is `-Eutf-8`, which is what was used in this package... however for some bizarre reason on macOS the option is `-E utf8` so it's likely that the encoding specification wasn't working at all on macOS.

**Comment by Arcanemagus** [comment] 2017-03-23 16:54
Closing as a duplicate of #103.

**Closed by Arcanemagus** 2017-03-23 16:54 UTC
Labels: bug

**Comment by artemgurzhii** [comment] 2017-03-23 17:38
How about this?
```js
let encoding = '-Eutf-8';
if (process.env._system_name === 'OSX') {
  encoding = '-E utf8';
}

const execArgs = ['-wc', encoding];
```

**Comment by artemgurzhii** [comment] 2017-03-23 17:46
It works for me!

**Comment by Arcanemagus** [comment] 2017-03-23 17:51
See comment in your #114 PR.
